name: MLflow CI + Docker Pipeline

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      # =========================
      # SETUP
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # =========================
      # INSTALL
      # =========================
      - name: Install dependencies
        run: |
          pip install mlflow pandas numpy scikit-learn matplotlib google-api-python-client google-auth

      # =========================
      # RUN MLFLOW PROJECT
      # =========================
      - name: Run MLflow Project
        run: |
          mlflow run MLProject

      # =========================
      # DEBUG RUN_ID
      # =========================
      - name: Debug RUN_ID file
        run: |
          ls -lah MLProject
          cat MLProject/run_id.txt

      # =========================
      # SET ENV RUN_ID
      # =========================
      - name: Set RUN_ID
        run: |
          echo "RUN_ID=$(cat MLProject/run_id.txt)" >> $GITHUB_ENV

      # =========================
      # UPLOAD GOOGLE DRIVE
      # =========================
      - name: Upload to Google Drive
        continue-on-error: true
        run: |
          cd MLProject
          python upload_to_drive.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      # =========================
      # BUILD DOCKER (FIXED)
      # =========================
      - name: Build Docker Model
        run: |
          mlflow models build-docker \
          -m runs:/${{ env.RUN_ID }}/model \
          -n insurance-model

      # =========================
      # LOGIN DOCKER
      # =========================
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # =========================
      # TAG IMAGE
      # =========================
      - name: Tag Docker Image
        run: |
          docker tag insurance-model ${{ secrets.DOCKER_USERNAME }}/insurance-model:latest

      # =========================
      # PUSH IMAGE
      # =========================
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/insurance-model:latest

      - name: Logout
        run: docker logout
