name: MLflow CI + Docker Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn matplotlib google-api-python-client google-auth

    # 🔥 DEBUG MODE (WAJIB)
    - name: Run MLflow Project (DEBUG)
      run: |
        mlflow run MLProject --env-manager=local

    # 🔍 DEBUG FILE
    - name: Debug files
      run: |
        ls -R

    - name: Debug RUN_ID
      run: |
        cat MLProject/run_id.txt

    - name: Set RUN_ID
      run: |
        echo "RUN_ID=$(cat MLProject/run_id.txt)" >> $GITHUB_ENV

    # Google Drive (tidak boleh gagalkan pipeline)
    - name: Upload to Google Drive
      continue-on-error: true
      run: |
        cd MLProject
        python upload_to_drive.py
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    # 🔥 BUILD DOCKER FIXED
    - name: Build Docker Model
      run: |
        mlflow models build-docker \
        -m runs:/${{ env.RUN_ID }}/model \
        -n insurance-model

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: |
        docker tag insurance-model ${{ secrets.DOCKER_USERNAME }}/insurance-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/insurance-model:latest

    - name: Logout
      run: docker logout